version: '3.1'
services:
  app:
    image: translator-app:latest
    environment:
      APP_ENVIRONMENT: production
      NEW_RELIC_LICENSE_KEY: foo
      NEW_RELIC_APP_NAME: translator-ui
    ports:
      - "8386:8386"
    depends_on:
      - pgdb
    command: ["configurations/production.json", "configurations/local-overrides.json"]
  pgdb:
    image: postgres:15.5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - ~/translator/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    secrets:
      - db_password
secrets:
  db_password:
    file: ./configurations/secrets/db_password
