---
  document-root: False
  port: 8386
  response-timeout: 300
  ars-endpoint:
    host: "ars-prod.transltr.io"
    post-uri: "/ars/api/submit"
    pull-uri: "/ars/api/messages"
  curie-search-endpoint:
    host: "name-resolution-sri.renci.org"
    uri: "/lookup"
  primary-predicates:
    - "treats"
    - "affects"
    - "disrupts"
    - "treated_by"
    - "entity_negatively_regulates_entity"
  mock-ars?: False
  mock-query?: False
  mock-pmid?: False
  mock-nct?: False
